### ISSUE TITLE
Testing errors

### ISSUE THREAD

**Issue by bmc** [arielscarpinelli/sbt-traceur#1]
With `sbt-traceur` in a Play 2.3.x app, running the `test` target within SBT (activator) fails. If there are no test classes under `test/assets/javascripts`, the following error occurs:

```
$ last web-assets-test:traceur
java.util.concurrent.TimeoutException: Futures timed out after [0 hours]
    at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
    at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
    at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
    at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
    at scala.concurrent.Await$.result(package.scala:107)
    at com.typesafe.sbt.jse.SbtJsTask$$anonfun$executeJs$1.apply(SbtJsTask.scala:401)
    at com.typesafe.sbt.jse.SbtJsTask$$anonfun$executeJs$1.apply(SbtJsTask.scala:397)
    at com.typesafe.sbt.web.SbtWeb$.withActorRefFactory(SbtWeb.scala:441)
    at com.typesafe.sbt.jse.SbtJsTask$.executeJs(SbtJsTask.scala:396)
    at com.typesafe.sbt.traceur.SbtTraceur$$anonfun$runTraceur$1.apply(SbtTraceur.scala:77)
    at com.typesafe.sbt.traceur.SbtTraceur$$anonfun$runTraceur$1.apply(SbtTraceur.scala:59)
        ...
```

I suspect this is because of the following line in `SbtTraceur.scala`:

``` scala
(timeoutPerSource in traceur).value * inputFileCandidates.size
```

If I add an empty Javascript `main.js` file under `test/assets/javascripts`, I get a different error:

```
[trace] Stack trace suppressed: run last web-assets-test:assets for the full output.
[error] (web-assets-test:assets) Duplicate mappings:
[error]     /home/bmc/src/mystuff/play/pwguard/pwguard/target/web/public/test/public/main.map
[error] from
[error]     /home/bmc/src/mystuff/play/pwguard/pwguard/target/web/resources-managed/main/javascripts/main.map
[error]         /home/bmc/src/mystuff/play/pwguard/pwguard/target/web/resources-managed/test/javascripts/main.map
[error]     /home/bmc/src/mystuff/play/pwguard/pwguard/target/web/public/test/public/main.js
[error] from
[error]     /home/bmc/src/mystuff/play/pwguard/pwguard/target/web/resources-managed/main/javascripts/main.js
...
```

Have you gotten testing to work at all with `sbt-traceur` in the mix?

**Comment by arielscarpinelli** [comment]
OK. I've fixed the issue. When no source files are found, the task is simply skipped.
Regarding your work-around, sadly sbt-web doesn't allow you to have repeated file paths, and files from "src" are combined with the ones from "test" for testing. So if you need some test specific javascript files (for instance, javascript tests!), my suggestion is to store them in test/assets/javascript-tests (and javascript-tests/main.js is going to be their default main module source path)

I'm going to publish 1.0.1 latter today with the fix

**Comment by arielscarpinelli** [comment]
Published

**Comment by fdietze** [comment]
Hi, the `1.0.1` release fixed my tests, but breaks play run. Traceur is not executed anymore.

Here are my settings:

``` scala
sourceFileNames := Seq("app/*/module.js", "app/*/*/**/*.js"),
```

Any ideas?

**Comment by arielscarpinelli** [comment]
Does module.js include any of the other files?
You are using one compiled file per original file approach right?

**Comment by cornerman** [comment]
No, module.js does not include any file, it just needs to be sourced before the other javascript files, because they depend on it. We compile all javascript files to one 'main.js' file.

**Comment by arielscarpinelli** [comment]
Well if module.js is imported by other files you shouldn't need to
explicitly add it unless you need to do some workaround with the import
paths

I'm curious then how to you are going to make the es6 code available to the
rest of the app if no file refers to other but your are building a main.js
output file?

**Comment by cornerman** [comment]
module.js is also not included directly by the other files. We use angular and just define our modules/services/controllers in the js files, so the whole app in the end is tied together by angular. Thus, only the module definitions (module.js) need to be executed before the rest of the app, as they need to be defined when used by the all the other js files.
